name: Build and Release EXE

on:
  push:
    tags:
      - 'v*' # Triggers when you push a tag like v1.0

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build EXE with PyInstaller
        # This command bundles everything into one file
        # It uses ; to separate folders because the runner is Windows
        run: |
          pyinstaller --noconfirm --onefile --windowed --name "EatThatCheese" --add-data "assets;assets" main.py

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/EatThatCheese.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}