name: Build EXE (Dev Branch)

on:
  # 1. Trigger when pushing to 'dev' branch
  push:
    branches: [ "dev" ]
  
  # 2. Trigger when pushing Tags (for final releases)
  create:
    tags:
      - 'v*'

  # 3. Allow Manual Button Click
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --name "EatThatCheese" --add-data "assets;assets" main.py

      # --- SCENARIO A: Pushed to 'dev' or Manual Click ---
      # Upload the EXE as a temporary "Artifact" (keeps it for 90 days)
      - name: Upload Dev Build
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/dev' || github.event_name == 'workflow_dispatch'
        with:
          name: EatThatCheese-Dev-Build
          path: dist/EatThatCheese.exe

      # --- SCENARIO B: Pushed a Tag (e.g. v1.0) ---
      # Create an official Release for the public
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/EatThatCheese.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}