name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'
  # --- THIS ENABLES THE MANUAL BUTTON ---
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --name "EatThatCheese" --add-data "assets;assets" main.py

      # Option 1: If triggered by TAG, make a Release
      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/EatThatCheese.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Option 2: If triggered MANUALLY, upload as a downloadable Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          name: EatThatCheese-Manual-Build
          path: dist/EatThatCheese.exe